baseURL = "http://La-Machine-à-Math.com/"
languageCode = "en-us"
title = "La Machine à Math"

defaultContentLanguage = 'fr'

[taxonomies]
  tag = "tags"
  lesson = "lessons"
  development = "developments"

[markup.goldmark.renderer]
  unsafe = true #used to enable custom styling useful to define spoilers
